---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/measured_variables - Sheet1/measured_variables - Sheet1.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/283731/master/file/figures/measured_variables%20-%20Sheet1/measured_variables%20-%20Sheet1.csv"
